platform: linux
image_resource:
    type: docker-image
    source:
        repository: alpine/git
        tag: latest
inputs:
- name: cf-blue-green-resource-source

outputs:
- name: version

run:
    path: /bin/sh
    args:
    - -exc
    - |
      cd cf-blue-green-resource-source
      ci/tasks/version.sh > ../version/version
