#!/bin/bash
set -e

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

request=$(mktemp --tmpdir cf-blue-green-resource-in.XXXXXX)

cat > $request <&0

DEST=$1

VERSION=$(jq -r '.version.timestamp // ""' < $request)

[[ -z "$VERSION" ]] && VERSION=$(date +%s)

echo "{\"version\": {\"timestamp\": $VERSION}}" | jq '.' >&3
